In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
data_dir = '/Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/'
metadata_file = '/Volumes/MEDICALDATA/physionet.org/outputs/for-pytorch/mimic_cxr_AP_pytorch.csv'
df_metadata = pd.read_csv(metadata_file)
display(df_metadata.head(10))

,Unnamed: 0.1,Unnamed: 0,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,...,anchor_age,anchor_year,anchor_year_group,dod,race,marital_status,hospital_expire_flag,disease,disease_label,img_filename
0,0,0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032.0,50414267.0,CHEST (PA AND LAT),PA,3056.0,2544.0,21800506.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s50414267/02aa804e-bde0afdd-112c...
1,1,1,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032.0,53189527.0,CHEST (PA AND LAT),PA,3056.0,2544.0,21800626.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53189527/2a2277a9-b0ded155-c0de...
2,2,2,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032.0,53911762.0,CHEST (PORTABLE AP),AP,2705.0,2539.0,21800723.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53911762/68b5c4b1-227d0485-9cc3...
3,3,3,fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818,10000032.0,53911762.0,CHEST (PORTABLE AP),AP,2906.0,2258.0,21800723.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53911762/fffabebf-74fd3a1f-673b...
4,4,4,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,10000032.0,56699142.0,CHEST (PORTABLE AP),AP,3056.0,2544.0,21800805.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s56699142/ea030e7a-2e3b1346-bc51...
5,5,5,096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4,10000764.0,57375967.0,CHEST (PA AND LAT),AP,2544.0,3056.0,21321015.0,...,86.0,2132.0,2014 - 2016,NaN,WHITE,SINGLE,0.0,Consolidation,2,p10/p10000764/s57375967/096052b7-d256dc40-453a...
6,6,6,2a280266-c8bae121-54d75383-cac046f4-ca37aa16,10000898.0,50771383.0,CHEST (PA AND LAT),PA,2544.0,3056.0,21880312.0,...,80.0,2188.0,2014 - 2016,NaN,NaN,NaN,NaN,No Finding,0,p10/p10000898/s50771383/2a280266-c8bae121-54d7...
7,7,7,b75df1bd-0f22d631-52d73526-2ae7b85a-d843b39d,10000898.0,54205396.0,CHEST (PA AND LAT),PA,3056.0,2544.0,21880113.0,...,80.0,2188.0,2014 - 2016,NaN,NaN,NaN,NaN,No Finding,0,p10/p10000898/s54205396/b75df1bd-0f22d631-52d7...
8,8,8,88498b37-c21dc7ba-bc202800-b517a62d-f7ac5bcf,10000935.0,58219844.0,CHEST (PORTABLE AP),AP,3056.0,2544.0,21871010.0,...,52.0,2182.0,2008 - 2010,2187-11-12,BLACK/AFRICAN AMERICAN,SINGLE,0.0,Other,4,p10/p10000935/s58219844/88498b37-c21dc7ba-bc20...
9,9,9,f1adcae3-2921c0a8-5d9652f9-4191ecd7-f2a96f35,10000935.0,56522600.0,NaN,PA,2022.0,1736.0,21860730.0,...,52.0,2182.0,2008 - 2010,2187-11-12,BLACK/AFRICAN AMERICAN,SINGLE,0.0,Other,4,p10/p10000935/s56522600/f1adcae3-2921c0a8-5d96...

In [3]:
preproc_dir = '/Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/preproc_224x224/'
# if not os.path.exists(preproc_dir): os.makedirs(preproc_dir)

In [4]:
# from skimage.io import imread
# from skimage.io import imsave
# from skimage.transform import resize
# import time

# # i=0
# t_start = time.time()
# for idx, p in df_metadata.iterrows():

#     jpgname = p['dicom_id']
#     newname = jpgname+'_resized.jpg'
#     out_path = preproc_dir + newname
    
#     if not os.path.exists(out_path):
#         img_path = data_dir + p['img_filename']
#         try:
#             image = imread(img_path)
#             image = resize(image, output_shape=(224, 224), preserve_range=True)
#             imsave(out_path, image.astype(np.uint8))
#             if (idx%1000)==0:
#                 print('#images resized: {}'.format(idx))
#                 print('time elapsed: {} min'.format((time.time()-t_start)/60))
#             if idx==100000:
#                 break
                
#         except FileNotFoundError:
#             print('File {} doesnt exist. Move to next...'.format(img_path))
#             continue
                
# print('Done.')
# print('Total time elapsed: {} min'.format((time.time()-t_start)/60))

#images resized: 0
time elapsed: 0.00646666685740153 min
#images resized: 1000
time elapsed: 4.647463862101237 min
#images resized: 2000
time elapsed: 9.09538923104604 min
#images resized: 3000
time elapsed: 13.64448409875234 min
#images resized: 4000
time elapsed: 17.978323260943096 min
#images resized: 5000
time elapsed: 22.388869595527648 min
#images resized: 6000
time elapsed: 26.239610167344413 min
#images resized: 7000
time elapsed: 30.499559048811594 min
#images resized: 8000
time elapsed: 34.76507967710495 min
#images resized: 9000
time elapsed: 38.880099479357405 min
#images resized: 10000
time elapsed: 43.307813044389086 min
#images resized: 11000
time elapsed: 47.83251174688339 min
#images resized: 12000
time elapsed: 53.87185796499252 min
#images resized: 13000
time elapsed: 59.14995696544647 min
#images resized: 14000
time elapsed: 64.54452544848124 min
#images resized: 15000
time elapsed: 70.03646306594213 min
#images resized: 16000
time elapsed: 75.44984234571457 min
#images resized: 17000
time elapsed: 80.48046889702479 min
#images resized: 18000
time elapsed: 85.19432199398676 min
#images resized: 19000
time elapsed: 90.04780188004176 min
#images resized: 20000
time elapsed: 94.9486141482989 min
#images resized: 21000
time elapsed: 100.06191728115081 min
#images resized: 22000
time elapsed: 104.95071098009745 min
#images resized: 23000
time elapsed: 109.38542624711991 min
#images resized: 24000
time elapsed: 113.76403374671936 min
#images resized: 25000
time elapsed: 118.27311667998632 min
#images resized: 26000
time elapsed: 124.45212939977645 min
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124151/s59447293/e5ff78d4-761e9b40-aee05e60-34bebcaf-249a9522.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124151/s56440298/a5841009-615cb1cc-3f1bdd69-f49e4939-51f7703a.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124151/s51025092/4c21a418-50fc7649-1576f010-358bb1fe-634a5033.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124151/s56439054/f1fb84bc-5e0c08b4-25d90cba-0184d6ad-3680ac49.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124186/s54427592/ec59905b-1302b7e4-a2d49e92-cde8b22a-2dea938c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124253/s54673366/d0ee3bbd-1fbeef20-ae401b03-c52eb178-c2d87088.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124253/s58167440/db3bddab-0ee13383-768f2b38-bec506d4-11d54721.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54990948/3bd0add0-45e4a6eb-7b9139af-05dfda5e-9b193549.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57516354/c8abd5cf-65284bae-12435c05-320cd599-0dd255fb.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57474669/e4c27d54-a056b9f6-6818effd-bf437b58-3ed45232.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57399182/eb1efd09-20deefd7-b5ada878-a3ab27b6-9fa0a800.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s56681984/66a50b5e-1790f7d0-44d07881-fe1e7c8c-aa2214eb.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57254512/072e0b35-771b350a-07e37d9e-312c983f-fdb77ce1.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57579023/d57142f6-d577c46b-4e74b232-7c523b73-e8dbc36f.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s56596422/e6cb026a-61ea8616-a2358343-08336ad6-7c90c3f2.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s56571285/bec9d832-d5de7eaf-14fb58c6-d971fef2-a8c742a7.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57399182/cd9405f8-81543cec-dae9f4fc-c82795ab-00776dfe.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57862717/3267e67d-5d898562-bf1cbc17-a6592a55-a820ccdf.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s58331311/ee2bf15f-d96a2611-4833d30d-5d9e9058-5f532f50.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57907252/f7dc8957-c7543973-c559a212-21fe643a-d0651614.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s58164054/9b6904bb-f6a6bb95-32d135fb-f08c7209-cdb64b3e.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s58581997/08483f26-d3bb5574-9522ad4e-62c1d16b-94052523.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s58581997/aa27a88b-a9cc160f-48701c9f-5e5fc236-e9894a0b.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s59955274/f8b74a3e-d56ab55b-a2100eaf-d9454338-df9e59f1.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s59134208/95d46df0-34d3be53-37ce65c5-1215e583-e5215365.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s59225926/7f4dd6d3-c7a4d9f1-a231e5f8-4b6f4741-0bca0bbd.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s59527912/a9b5f452-2237c1e2-a42296e7-a2b1c671-433617b9.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s59527912/d1cd0420-bc4bef35-b59d57f5-e737f066-757d4d2c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s57907252/eb607eeb-18d10b8f-bc79d60b-fead9bfd-f07891ad.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54867867/a25cb8d2-ae135614-8801734c-d76b8204-110e0179.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54827982/ade34224-18666623-496faf29-bfbf8978-43a2a5df.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54867867/706eb6ac-948fcb17-16201431-7aa47c96-869c8325.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s50155102/02b5d6dd-45c25033-20098a6b-72a9c88e-8e86cbbe.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s50254338/5da74cf4-13e74efa-3340b69e-325c8f2c-049eee4d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s50631255/1fe6c832-b2f007a5-33444362-462aff9b-8570d733.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s50968783/5eb4f616-9ba12e23-13686313-e84a48f3-079b842c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s51739989/a7f28322-d106fce6-8ac2a7ce-b8f453da-1c76665c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52473039/8eeef264-806717a9-6d2cce90-a5bd8c7a-bb48db26.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52819409/3c097888-643a9a45-b5084449-3aa16966-51ccd590.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52819409/583cb44c-0ba13dd8-df9403fd-815260a0-aac16006.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52960556/1826788f-cd5c71ff-98ef0161-315c6ece-40ae0c6c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52972230/6fbd1aaf-c24a03c4-31c15638-c3083086-f97386ba.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52972230/96c00e0b-15a0c9aa-b6c8547a-52d65b8f-891260ff.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s50155102/1168394b-6b81767d-bb36017d-64e9bbfc-cccc69b8.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s53453335/bffae0bd-e7b80391-7c8bf64b-9352ed72-cb5d9e11.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s52972230/af30a59d-fcda3da0-6c606c3f-da7d0e04-e80fee07.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54716148/bbbacc8f-781fcdfd-e9ac77db-01bd44cd-e4d583bb.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54566416/e693cd9e-55f43269-52dcbe85-2b183602-a2b29b2a.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54414478/ffc6a3ec-1c5ffb6f-e1761c3d-e157a8e1-1768d0f0.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54667879/5f456c80-d2444168-36d9c0b2-653466fb-ae191905.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54326095/1994c5f5-0c7a873a-b238fb01-3f6d0587-14a892fd.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s53568337/a974bb6b-8513fec9-a21a5c9a-218ec8c6-aaf8de1d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s53568337/7f49f3d1-a9b601d1-f43b0717-5ff58889-16fc4f3b.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s53453335/def764cd-fefc11eb-37812054-b2d5c7a9-c53cebfe.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124675/s54339042/a07e3d0f-d1c0cc20-456eed8c-6646e616-ed285e23.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124729/s54378860/e409b936-84920458-79d99736-43eda2a9-a0e68696.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124729/s58720257/aacdb3ec-d0c4aa6e-c0deb9ae-b7e8a749-38934473.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124744/s51055950/09f0a715-d4c645ee-5fbe80f4-e8da17a4-c20a663d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s57088664/6569208d-8463df7a-9461a51f-1e3a7cd0-c7c5ea3e.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s56192516/e79a8889-7be247f1-8a2b2bab-8e2a8fb2-774c1ecb.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s56332418/79b5a708-e2f40c70-6a451c4c-9e45b22a-b8395692.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s56982819/e819d02a-33caca9b-c174a023-dcb38353-89bdffc9.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s57122675/d5613181-d7897d33-647a2035-4e0b5917-0409bbd5.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s59794837/f6976503-bca9421d-2511e904-578b24fa-3760bf85.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s58927606/feb9bc5c-43cc37eb-60766b7b-21f447ea-03f01526.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s59129085/18be92a6-4ac6affc-2324bd9d-36a418db-319f84dc.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s59184766/fa6df92c-4de21bea-3c2c7c06-0cfb20be-141f5b0d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s59711046/41c7d661-8f90d28d-d0fcc99d-820ab61a-48fecbbc.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s59826630/241b6bda-ea6156e2-3b254b31-1e07a105-ca7d866c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s56068480/49df60ea-222c7f47-963e0ed7-8a1020ad-b7663db0.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s58402516/10b14863-85f07d58-8b6664e7-81bc8802-101017f0.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s55663368/cc3c2016-ee65c79a-24689446-3a729250-753cecfc.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s56192516/b382f019-295544f0-023d5efc-16307e6f-c585eaaf.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s50289493/593a8ba5-3ed083b7-a8a59f01-d5de83be-21ad91e9.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s50564151/45ae4df1-2ad85d35-fe7648b8-3bb026fb-1f6697c3.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s50665376/061c1c1a-ad508d7f-09879863-c6a67cb2-1c9c6733.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s51135265/1e45ea48-e29839fa-d7ee565a-397802f3-f55a15de.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s51511656/5071e7b5-d29787e6-be0d3479-d13fc52a-c4411737.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s51868297/1c1ba636-7d3d646a-54009565-381bb61e-05fbd758.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s51988125/fbb95a89-18e18729-46340b4a-72eb9898-d11e17ea.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s51868297/e39494b3-6de93433-dc049e78-7b0456b9-8f2307e9.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s54279083/0d92dc95-3db0e95d-0666acb5-0ea16a0a-0c5b5457.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s54021091/be5075c2-cb6796f6-4bedf55c-f908765e-0b25f36c.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s55417501/3f1db8a6-c8276fe8-1a7cc69c-fac2b94f-7af1fc49.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s53036569/84b12b40-bd98ec90-2f8043b2-36d3b1d4-57585691.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s52034268/e7c80410-c0b6268e-a34f9cd4-d0413598-f840a22f.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124859/s53742677/5c519707-2a4331be-f235baf9-6853d287-497569ed.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11124983/s51629156/cefae3e7-c0802be7-a14ab9a9-54c67dab-5c3a8b3d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125170/s58181750/95cd957a-59270c33-1545f610-a2439270-598f593b.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125220/s59895516/916f0bab-7af1d305-001c787a-c3c6ce81-63dd55f4.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125269/s54073429/06d4c5d6-9a0f28df-552b54a7-ef6dce6d-b5063dff.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125351/s50669410/ddb59b36-ba1cb07c-4a2bf520-f6f691fa-e300fff3.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125370/s58963570/069cc1d2-20b8b2f0-abc91cbf-b7de579d-97e36a96.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125404/s57157233/fef366b0-f425827a-510bee18-ee1774b1-83f16296.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125422/s52820918/0f8e3621-dd328092-26c8bace-109a44ab-8baa3343.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125653/s53199299/595e1508-1d4d20e3-3bce95d1-604574ac-8f3955f8.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125800/s52918749/f1511bca-debab4e9-e178c85a-2275df3a-82261fd3.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125800/s58515823/ab689e57-e94fb589-3ceb5ea5-e9c98bdd-1ba6de3a.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125965/s56591635/ee3d34a8-7c9c7fe8-2d1b1401-29dc38d9-96ace3ad.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11125965/s51096367/6011de1d-a592380c-f952c480-a0d23f2a-f90dc4c4.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11126209/s59752674/0223d005-dbaa2f22-8aea17c3-9948343e-834efce7.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11126363/s50923594/dce79ece-b0fd4e76-573eb7fa-4c14924a-20b636a2.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11126363/s55463946/6aa897cd-80021faa-21a97896-b2423012-9c625428.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11126363/s58018671/5e4a00a7-0d2b3174-82d6a509-f13ae7ef-56e5aa7d.jpg doesnt exist. Move to next...
File /Volumes/MEDICALDATA/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p11/p11126363/s59041590/3ef79017-230644c5-cae510ba-077811b5-d4b5f937.jpg doesnt exist. Move to next...

KeyboardInterrupt:

In [4]:
# given a subset of the data, make a new metadata file corresponding to the patient subset
img_subset_path = preproc_dir
df_metadata_subset = pd.DataFrame(columns=df_metadata.columns)
i=0
files=[]
for file in os.listdir(img_subset_path):
    i+=1
    if i==1:
        f = file.strip('_resized.jpg')
        df_f = df_metadata.loc[df_metadata['dicom_id']==f, :]
        df_metadata_subset = pd.concat([df_metadata_subset, df_f], ignore_index=True)
        files.append(file)
        # display(df_metadata_subset)
    elif file in files:
        print('duplicate')
        continue
    else:
        f = file.strip('_resized.jpg')
        df_f = df_metadata.loc[df_metadata['dicom_id']==f, :]
        df_metadata_subset = pd.concat([df_metadata_subset, df_f], ignore_index=True)
        files.append(file)

    if (i%1000)==0:
        print(i)

/var/folders/rz/h7cm1h2j06vbbj_t9vl0ktk80000gn/T/ipykernel_9440/2742263082.py:11: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metadata_subset = pd.concat([df_metadata_subset, df_f], ignore_index=True)

1000
2000
3000
4000
5000

KeyboardInterrupt:

In [5]:
df_metadata_subset = df_metadata_subset.drop_duplicates('dicom_id')
display(df_metadata_subset)

,Unnamed: 0.1,Unnamed: 0,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,...,anchor_age,anchor_year,anchor_year_group,dod,race,marital_status,hospital_expire_flag,disease,disease_label,img_filename
0,0,0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032.0,50414267.0,CHEST (PA AND LAT),PA,3056.0,2544.0,21800506.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s50414267/02aa804e-bde0afdd-112c...
2,1,1,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032.0,53189527.0,CHEST (PA AND LAT),PA,3056.0,2544.0,21800626.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53189527/2a2277a9-b0ded155-c0de...
4,2,2,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032.0,53911762.0,CHEST (PORTABLE AP),AP,2705.0,2539.0,21800723.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53911762/68b5c4b1-227d0485-9cc3...
6,3,3,fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818,10000032.0,53911762.0,CHEST (PORTABLE AP),AP,2906.0,2258.0,21800723.0,...,52.0,2180.0,2014 - 2016,2180-09-09,WHITE,WIDOWED,0.0,No Finding,0,p10/p10000032/s53911762/fffabebf-74fd3a1f-673b...
8,5,5,096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4,10000764.0,57375967.0,CHEST (PA AND LAT),AP,2544.0,3056.0,21321015.0,...,86.0,2132.0,2014 - 2016,NaN,WHITE,SINGLE,0.0,Consolidation,2,p10/p10000764/s57375967/096052b7-d256dc40-453a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4072,2633,2633,f748dc77-cf6b6ee8-a047e48c-8864f593-bcb1a9a2,10118141.0,59450151.0,CHEST (PORTABLE AP),AP,2544.0,3056.0,21780527.0,...,43.0,2178.0,2014 - 2016,2178-05-28,UNKNOWN,NaN,1.0,Other,4,p10/p10118141/s59450151/f748dc77-cf6b6ee8-a047...
4074,2635,2635,ad1f97b9-12f7d4b8-72bfa442-c77f6800-3fce375b,10118626.0,51904237.0,CHEST (PORTABLE AP),AP,2544.0,3056.0,21540814.0,...,60.0,2153.0,2014 - 2016,NaN,BLACK/AFRICAN AMERICAN,SINGLE,0.0,No Finding,0,p10/p10118626/s51904237/ad1f97b9-12f7d4b8-72bf...
4076,2637,2637,faf18b22-c2b3d146-3782b926-1a0de07f-0f608a3c,10119391.0,51318265.0,CHEST (PA AND LAT),AP,3056.0,2544.0,21930504.0,...,75.0,2188.0,2008 - 2010,2198-08-08,WHITE,MARRIED,0.0,Other,4,p10/p10119391/s51318265/faf18b22-c2b3d146-3782...
4078,2638,2638,a018fb95-5a5e0cbc-3b5a2dd9-8d110a45-42f155f2,10119391.0,57613229.0,CHEST (PA AND LAT),AP,3056.0,2544.0,21930605.0,...,75.0,2188.0,2008 - 2010,2198-08-08,WHITE,MARRIED,0.0,No Finding,0,p10/p10119391/s57613229/a018fb95-5a5e0cbc-3b5a...
4080,2639,2639,91ba8fc1-ad8f974f-51c7b990-9c98905c-43a4315f,10119514.0,55199923.0,CHEST (PORTABLE AP),AP,2544.0,2933.0,21920228.0,...,85.0,2188.0,2008 - 2010,NaN,WHITE - RUSSIAN,MARRIED,0.0,No Finding,0,p10/p10119514/s55199923/91ba8fc1-ad8f974f-51c7...

In [5]:
out_dir = '/Volumes/MEDICALDATA/physionet.org/outputs/for-pytorch'
# df_metadata_subset.to_csv(os.path.join(out_dir, 'metadata.csv'))

In [6]:
df_metadata_subset_done = pd.read_csv(os.path.join(out_dir, 'metadata_preproc_224x224.csv')).drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
df_metadata_subset_done.shape

(29862, 41)

In [7]:
names = []
for idx, p in df_metadata_subset_done.iterrows():
    filename = p['dicom_id']
    filename += '_resized.jpg'
    names.append(filename)

In [8]:
df_metadata_subset_done['img_preproc_filename'] = names
display(df_metadata_subset_done['img_preproc_filename'])

0        02aa804e-bde0afdd-112c0b34-7bc16630-4e384014_r...
1        2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab_r...
2        68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714_r...
3        fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818_r...
4        096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4_r...
                               ...
29857    6a4ef535-7eae3d13-4ac2340c-a8ef844d-dedb3eaf_r...
29858    ce8866d6-a3fc0023-00fb8f22-a7560e10-fb7a7ee9_r...
29859    9ead4e6c-613ebe2f-27f24892-02fb4e8b-0d59ee1c_r...
29860    7eb75010-e0398a69-ab9f2ddc-77fc366a-7e871477_r...
29861    1e31075c-48f6b01d-dfd7f8c7-cb5b1324-cea75faa_r...
Name: img_preproc_filename, Length: 29862, dtype: object

In [10]:
df_metadata_subset_done.to_csv(os.path.join(out_dir, 'metadata_preproc_224x224_done1.csv'))